stages:
  - build_and_deploy

# 把 打包 + 部署 放在同一个阶段，不拆分！
# 这样目录不会变，文件不会丢！
build_and_deploy_all:
  stage: build_and_deploy
  script:
    # 1. 打包
    - mvn clean package -DskipTests -P fat-jar

    # 2. 查看 jar（你能看到）
    - find . -name "*.jar" | grep -v test

    # 3. 准备私钥
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key

    # ==================== 部署 admin ====================
    - rsync -avz -e "ssh -p 22 -i private_key -o StrictHostKeyChecking=no" continew-server/target/continew-admin.jar root@52.195.156.13:/opt/employee/webapi/
    - ssh -p 22 -i private_key root@52.195.156.13 "
      cd /opt/employee/webapi &&
      mkdir -p bak &&
      [ -f continew-admin.jar ] && cp continew-admin.jar bak/continew-admin.jar.$(date +%Y%m%d%H%M%S) &&
      sh api-service.sh stop && sleep 3 && sh api-service.sh start
      "

    # ==================== 部署 customer ====================
    - rsync -avz -e "ssh -p 22 -i private_key -o StrictHostKeyChecking=no" continew-customer/target/continew-customer.jar root@52.195.156.13:/opt/employee/clientapi/
    - ssh -p 22 -i private_key root@52.195.156.13"
      cd /opt/employee/clientapi &&
      mkdir -p bak &&
      [ -f continew-customer.jar ] && cp continew-customer.jar bak/continew-customer.jar.$(date +%Y%m%d%H%M%S) &&
      sh api-client.sh stop && sleep 3 && sh api-client.sh start
      "

  when: manual
  only:
    - main


# 打包后端
build_and_deploy_admin:
  stage: build_and_deploy
  script:
    # 1. 打包
    - mvn clean package -DskipTests -P fat-jar

    # 2. 查看 jar（你能看到）
    - find . -name "*.jar" | grep -v test

    # 3. 准备私钥
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key

    # ==================== 部署 admin ====================
    - rsync -avz -e "ssh -p 22 -i private_key -o StrictHostKeyChecking=no" continew-server/target/continew-admin.jar root@52.195.156.13:/opt/employee/webapi/
    - ssh -p 22 -i private_key root@52.195.156.13 "
      cd /opt/employee/webapi &&
      mkdir -p bak &&
      [ -f continew-admin.jar ] && cp continew-admin.jar bak/continew-admin.jar.$(date +%Y%m%d%H%M%S) &&
      sh api-service.sh stop && sleep 3 && sh api-service.sh start
      "

  when: manual
  only:
    - main

# 打包客户端
build_and_deploy_customer:
  stage: build_and_deploy
  script:
    # 1. 打包
    - mvn clean package -DskipTests -P fat-jar

    # 2. 查看 jar（你能看到）
    - find . -name "*.jar" | grep -v test

    # 3. 准备私钥
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key

    # ==================== 部署 customer ====================
    - rsync -avz -e "ssh -p 22 -i private_key -o StrictHostKeyChecking=no" continew-customer/target/continew-customer.jar root@52.195.156.13:/opt/employee/clientapi/
    - ssh -p 22 -i private_key root@52.195.156.13 "
      cd /opt/employee/clientapi &&
      mkdir -p bak &&
      [ -f continew-customer.jar ] && cp continew-customer.jar bak/continew-customer.jar.$(date +%Y%m%d%H%M%S) &&
      sh api-client.sh stop && sleep 3 && sh api-client.sh start
      "

  when: manual
  only:
    - main