<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.admin</groupId>
        <artifactId>continew-admin</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-customer</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>客户端 API 模块</description>

    <dependencies>
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-common</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- ContiNew Starter 链路追踪模块 -->
        <dependency>
            <groupId>top.continew.starter</groupId>
            <artifactId>continew-starter-trace</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>continew-customer</finalName>
        <plugins>
            <!-- Spring Boot 可执行 JAR 打包插件 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <!-- 指定主启动类 -->
                    <mainClass>top.continew.admin.customer.CustomerApplication</mainClass>
                    <!-- 是否将系统作用域的依赖包含进去 -->
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!-- 胖包模式：将依赖、配置文件等打包到 jar 包之内 -->
        <profile>
            <id>fat-jar</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <!-- 指定主启动类 -->
                            <mainClass>top.continew.admin.customer.CustomerApplication</mainClass>
                            <!-- 是否将系统作用域的依赖包含进去 -->
                            <includeSystemScope>true</includeSystemScope>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
